name: Hello
on:
    push:
        branches:
            - main
        paths:
            - 'sample/**/*.py'
        paths-ignore:
            - 'sample/**/*.md'
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello, world!"
            - uses: actions/checkout@v4
